export default [
  { name: "Avatar 1", value: "/images/players/avatar-01.svg" },
  { name: "Avatar 2", value: "/images/players/avatar-02.svg" },
  { name: "Avatar 3", value: "/images/players/avatar-03.svg" },
  { name: "Avatar 4", value: "/images/players/avatar-04.svg" },
  { name: "Avatar 5", value: "/images/players/avatar-05.svg" },
  { name: "Avatar 6", value: "/images/players/avatar-06.svg" },
  { name: "Avatar 7", value: "/images/players/avatar-07.svg" },
  { name: "Avatar 8", value: "/images/players/avatar-08.svg" },
  { name: "Avatar 9", value: "/images/players/avatar-09.svg" },
  { name: "Avatar 10", value: "/images/players/avatar-10.svg" },
  { name: "Avatar 11", value: "/images/players/avatar-11.svg" },
  { name: "Avatar 13", value: "/images/players/avatar-13.svg" },
  { name: "Avatar 14", value: "/images/players/avatar-14.svg" },
  { name: "Avatar 15", value: "/images/players/avatar-15.svg" },
  { name: "Avatar 16", value: "/images/players/avatar-16.svg" },
];
